# Custom Language File for Launcher Customizer

[ejs.app]
title = "도화 온라인"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/DoHwa"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/SCxVZxCfDR"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/DoHwa"
supportLink = "https://github.com/CustomLauncherLab/DoHwa/issues"

[ejs.welcome]
welcomeHeader = "도화 온라인"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."
